## database ##
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.112.255.207/customerflow?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: guonumber1
  #reids数据源
  redis:
     host: 127.0.0.1
     port: 6379
     timeout: 6000
     jedis:
       pool:
         max-active: 10000  # 连接池最大连接数（使用负值表示没有限制）
         max-wait: 10000      # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-idle: 3000      # 连接池中的最大空闲连接
         min-idle: 1000       # 连接池中的最小空闲连接
  jackson:
      time-zone: GMT+8

## port ##
server:
  port: 8081

## mybatis ##
mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.carry.customerflow.bean
